sudo: false
language: java
dist: xenial
jdk:
  - openjdk8
before_install:
  - cp .travis.settings.xml $HOME/.m2/settings.xml
deploy:
  provider: script
  script:
    - "cp .travis.settings.xml $HOME/.m2/settings.xml"
    - "mvn -B deploy"
  skip_cleanup: true
after_success:
  - mvn clean cobertura:cobertura coveralls:cobertura